name: Deploy on Tag or Manual

on:
  push:
    tags:
      - '*'
  workflow_dispatch: 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install hugo-extended and httrack via chocolatey
      working-directory: .
      run: |
           choco install hugo-extended --version 0.57.2
           # choco install httrack

    - name: Build into ./public
      working-directory: .
      run: |
           hugo --theme book

    #- name: deploy
    #  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
    #  with:
    #      username: 'tbd'
    #      server: 'tbd'
    #      ssh_private_key: ${{ secrets.UM_PRIVATE_KEY }}
    #      local_path: './public/*'
    #      remote_path: '.../some_public'
    - name: samkirkland.deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: TBD
        username: TBD
        password: ${{ secrets.password }}
        local-dir: ./public/
        server-dir: some/folder/

    
